### ISSUE TITLE
Update About section

### ISSUE THREAD

**Issue by vicky002** [demidovakatya/demidovakatya.github.io#1]
Hi @demidovakatya , just checkout your git portfolio page. About [section](http://demidovakatya.github.io/about/) is not updated. To update your about page, make changes in this [file](https://github.com/demidovakatya/demidovakatya.github.io/blob/master/about.md).

Site looks good! :+1:

You can refer my Git page : [EulerCoder](http://eulercoder.me)

**Comment by demidovakatya** [comment]
thanks, I forgot about it :santa:

**Comment by demidovakatya** [comment]
done
